name: "[CD] Continuous Delivery"

# Sempre que tiver um commit ou PR aberto
on:
  pull_request:
    types: [opened, synchronize]
  push: 
    branches: [ main ]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
          ## [Common_CI_Steps]
          - uses: actions/checkout@v4
          ## ================
          - name: "Debug"
            run: |
              ls -la
          - name: "Install Dependencies"
            run: "npm ci"
          - name: "Deploy"
            run: "npx vercel --prod"